### ISSUE TITLE
cannot import name OCR

### ISSUE THREAD

**Issue by getcontrol** [NanoNets/nanonets-id-card-digitization#1]
Followed the directions.I have nanonets installed.

_From pip list:_
_nanonets           2.0.1_    

After  inputting` python ./code/training.py` in directory nanonets-id-card-digitization/
get error:

Traceback (most recent call last):
  File "./code/training.py", line 2, in <module>
    from nanonets import OCR
ImportError: cannot import name OCR

**Comment by codeaway23** [comment]
can you please tell me exactly the steps to recreate the error? Also details about the python version.

**Comment by getcontrol** [comment]
Solved with using venv
